export const title = 'Ultimate Mission Maker EX';
export const author = 'Vashiru, j00rtje, DanielOnDiordna, McBen';

// questions for current Mission number
export const MissionNumberQuestions = [
  "What number is this mission ?",
  "Which mission number is this ?",
  "What is the mission number ?",
  "Which number does this mission have ?",
  "What is this mission’s number ?",
  "Which mission index is this ?",
  "What is the index of this mission ?",
  "Which position does this mission have ?",
  "What is the position of this mission ?",
  "Which mission slot is this ?",
  "What number does this mission have in the banner ?",
  "Which banner number is this mission ?",
  "What is this mission’s banner position ?",
  "Which mission number is shown in the banner ?",
  "What number identifies this mission in the series ?",
  "Which number does this mission have in the sequence ?",
  "What is the mission’s number in the series ?",
  "Which mission position is this in the banner ?",
  "What number is assigned to this banner mission ?",
  "Which number marks this mission in the banner ?",
  "What mission number are you playing right now ?",
  "Which mission number are you currently on ?",
  "What number are you on in this banner ?",
  "Which mission number are you completing now ?",
  "What is the current mission number ?",
  "Which number is this step of the banner ?",
  "What number is this step in the mission series ?",
  "Which mission step number is this ?",
  "What is the step number of this mission ?",
  "Which number corresponds to this mission step ?",
  "Identify the mission number of this mission.",
  "Select the mission number for this mission.",
  "Determine this mission’s number.",
  "State the number of this mission.",
  "Indicate the index of this mission.",
  "Specify the position number of this mission.",
  "What ordinal number does this mission have ?",
  "Which ordinal position is this mission ?",
  "What numeric identifier does this mission have ?",
  "Which numeric index applies to this mission ?",
  "What is the mission number you are answering ?",
  "Which number corresponds to this exact mission ?",
  "What number is displayed for this mission ?",
  "Which mission number is written here ?",
  "What is the official number of this mission ?",
  "Which mission number was assigned here ?",
  "What number labels this mission ?",
  "Which number tags this mission ?",
  "What is the mission’s assigned number ?",
  "Which number marks this mission ?",
  "What is this mission’s index number ?",
  "Which index number is this mission ?",
  "What is the banner index of this mission ?",
  "Which banner index applies here ?",
  "What position number does this mission have ?",
  "Which position number is this mission ?",
  "What is the mission’s position number ?",
  "Which slot number is this mission ?",
  "What is this mission’s slot number ?",
  "Which slot position is this mission ?",
  "What number identifies this mission in the banner ?",
  "Which number identifies this mission in the banner ?",
  "What is the number assigned to this mission ?",
  "Which number is assigned to this mission ?",
  "What is this mission’s series number ?",
  "Which series number is this mission ?",
  "What is the banner series number of this mission ?",
  "Which banner series number is this mission ?",
  "What number corresponds to this banner entry ?",
  "Which number corresponds to this banner entry ?"
];

// random questions
export const NoobQuestions = [
  { q: "What is the capital of France?", a: "Paris" },
  { q: "What is the capital of Germany?", a: "Berlin" },
  { q: "What is the capital of Italy?", a: "Rome" },
  { q: "What is the capital of Spain?", a: "Madrid" },
  { q: "What is the capital of the United Kingdom?", a: "London" },
  { q: "What is the capital of Japan?", a: "Tokyo" },
  { q: "What is the capital of China?", a: "Beijing" },
  { q: "What is the capital of Australia?", a: "Canberra" },
  { q: "What is the capital of Canada?", a: "Ottawa" },
  { q: "What is the capital of Austria?", a: "Vienna" },
  { q: "How many days are in a week?", a: "7" },
  { q: "How many months are in a year?", a: "12" },
  { q: "How many hours are in a day?", a: "24" },
  { q: "How many minutes are in an hour?", a: "60" },
  { q: "How many seconds are in a minute?", a: "60" },
  { q: "How many continents are there?", a: "7" },
  { q: "How many letters are in the English alphabet?", a: "26" },
  { q: "What is 1 + 1?", a: "2" },
  { q: "What is 2 + 2?", a: "4" },
  { q: "What is 3 + 3?", a: "6" },
  { q: "What is 4 + 4?", a: "8" },
  { q: "What is 5 + 5?", a: "10" },
  { q: "What is 10 - 5?", a: "5" },
  { q: "What is 7 - 2?", a: "5" },
  { q: "What is 6 + 1?", a: "7" },
  { q: "What is 9 - 3?", a: "6" },
  { q: "What animal says meow?", a: "Cat" },
  { q: "What animal says woof?", a: "Dog" },
  { q: "What animal says moo?", a: "Cow" },
  { q: "What color is grass?", a: "Green" },
  { q: "What color is snow?", a: "White" },
  { q: "What color is coal?", a: "Black" },
  { q: "What color is the sun?", a: "Yellow" },
  { q: "Is the Earth round?", a: "Yes" },
  { q: "Is fire hot?", a: "Yes" },
  { q: "Is ice cold?", a: "Yes" },
  { q: "Is the sky usually blue?", a: "Yes" },
  { q: "Is water wet?", a: "Yes" },
  { q: "Is the sun a star?", a: "Yes" },
  { q: "Is the moon a satellite of Earth?", a: "Yes" },
  { q: "What is the name of the blue faction in Ingress?", a: "Resistance" },
  { q: "What is the name of the green faction in Ingress?", a: "Enlightened" },
  { q: "What is Ingress energy called?", a: "XM" },
  { q: "What is a basic item deployed on portals?", a: "Resonator" },
  { q: "How many sides does a triangle have?", a: "3" },
  { q: "How many sides does a square have?", a: "4" },
  { q: "How many sides does a pentagon have?", a: "5" },
  { q: "How many wheels does a car usually have?", a: "4" },
  { q: "How many legs does a spider have?", a: "8" },
  { q: "How many fingers does a human have?", a: "10" },
  { q: "What planet do we live on?", a: "Earth" },
  { q: "What star is at the center of our solar system?", a: "Sun" },
  { q: "What is frozen water called?", a: "Ice" },
  { q: "What is water vapor called?", a: "Steam" },
  { q: "What is the opposite of hot?", a: "Cold" },
  { q: "What is the opposite of big?", a: "Small" },
  { q: "What is the opposite of day?", a: "Night" },
  { q: "What comes after Monday?", a: "Tuesday" },
  { q: "What comes after Tuesday?", a: "Wednesday" },
  { q: "What comes after Wednesday?", a: "Thursday" },
  { q: "What comes after Thursday?", a: "Friday" },
  { q: "What comes after Friday?", a: "Saturday" },
  { q: "What comes after Saturday?", a: "Sunday" },
  { q: "Is 0 an even number?", a: "Yes" },
  { q: "Is 2 an even number?", a: "Yes" },
  { q: "Is 3 an odd number?", a: "Yes" },
  { q: "Is 10 greater than 5?", a: "Yes" },
  { q: "Is 1 less than 2?", a: "Yes" },
  { q: "What is the first month of the year?", a: "January" },
  { q: "What is the last month of the year?", a: "December" },
  { q: "How many seasons are there?", a: "4" },
  { q: "What season comes after spring?", a: "Summer" },
  { q: "What season comes after summer?", a: "Autumn" },
  { q: "What season comes after autumn?", a: "Winter" },
  { q: "What color is the Resistance faction?", a: "Blue" },
  { q: "What color is the Enlightened faction?", a: "Green" },
  { q: "What does GPS stand for?", a: "Global Positioning System" },
  { q: "What is the shape of the Earth?", a: "Round" },
  { q: "What is the natural satellite of Earth called?", a: "Moon" },
  { q: "What is the largest planet in the solar system?", a: "Jupiter" },
  { q: "What is the closest star to Earth?", a: "Sun" },
  { q: "What do you call frozen precipitation?", a: "Snow" },
  { q: "What do you call liquid precipitation?", a: "Rain" },
  { q: "What is the name of the blue faction?", m: "Resistance,Enlightened,Neutral,Shapers" },
  { q: "What is the name of the green faction?", m: "Enlightened,Resistance,Neutral,Niantic" },
  { q: "What is the energy in Ingress called?", m: "XM,AP,MU,HP" },
  { q: "What is the basic portal item called?", m: "Resonator,Shield,Key,Mod" },
  { q: "What item links two portals?", m: "Link,Field,Shield,Key" },
  { q: "What item creates a field?", m: "Control Field,Link,Resonator,XMP" },
  { q: "What device do you use to play Ingress?", m: "Scanner,Portal,Beacon,Drone" },
  { q: "What is the maximum portal level?", m: "8,16,10,5" },
  { q: "How many resonators can a portal have?", m: "8,4,6,10" },
  { q: "What is the color of the Resistance?", m: "Blue,Green,Red,Yellow" },
  { q: "What is the color of the Enlightened?", m: "Green,Blue,Red,Yellow" },
  { q: "What is a neutral portal called?", m: "Neutral,Empty,Gray,Wild" },
  { q: "What item removes enemy resonators?", m: "XMP Burster,Shield,Key,Resonator" },
  { q: "What item removes links and fields?", m: "Ultra Strike,XMP Burster,Shield,Key" },
  { q: "What item increases link range?", m: "Link Amp,Shield,Key,Resonator" },
  { q: "What item increases portal defense?", m: "Shield,Link Amp,Key,Resonator" },
  { q: "What do you deploy to increase portal level?", m: "Resonator,Shield,Key,Link" },
  { q: "What do you use to recharge portals?", m: "Power Cube,Resonator,Shield,Link Amp" },
  { q: "What is the maximum agent level?", m: "16,8,10,20" },
  { q: "What does AP stand for?", m: "Action Points,Agent Power,Access Points,Action Portals" },
  { q: "What does MU stand for?", m: "Mind Units,Map Units,Mission Units,Memory Units" },
  { q: "What is the official Ingress map called?", m: "Intel,Scanner,Portal Map,XM Map" },
  { q: "What is a portal key used for?", m: "Linking,Hacking,Recharging,Shielding" },
  { q: "What is the Enlightened flip item?", m: "ADA Refactor,Jarvis Virus,XMP,Link Amp" },
  { q: "What is the Resistance flip item?", m: "Jarvis Virus,ADA Refactor,XMP,Shield" },
  { q: "What is a group of missions called?", m: "Banner,Cluster,Series,Pack" },
  { q: "What do you call fields inside fields?", m: "Nested Fields,Double Links,Overlays,Stacked Links" },
  { q: "What is the term for destroying a portal?", m: "Neutralizing,Capturing,Hacking,Linking" },
  { q: "What is the term for capturing a portal?", m: "Capturing,Neutralizing,Linking,Fielding" },
  { q: "What is the term for repeated hacking?", m: "Glyph Hacking,Power Hacking,Fast Hacking,Multi Hacking" },
  { q: "What is the maximum resonator level?", m: "8,16,10,5" },
  { q: "What is the lowest resonator level?", m: "1,0,2,3" },
  { q: "What is the default neutral color?", m: "Gray,Blue,Green,Red" },
  { q: "What is the color of Resistance fields?", m: "Blue,Green,Yellow,Red" },
  { q: "What is the color of Enlightened fields?", m: "Green,Blue,Yellow,Red" },
  { q: "What is a portal farm called?", m: "Farm,Cluster,Base,Hub" },
  { q: "What is a dense portal area called?", m: "Cluster,Farm,Hub,Base" },
  { q: "What item boosts hack output?", m: "Heat Sink,Multi-hack,Shield,Link Amp" },
  { q: "What item boosts hack rarity?", m: "Multi-hack,Heat Sink,Shield,Resonator" },
  { q: "What is a long-distance link called?", m: "Long Link,Ultra Link,Far Link,Wide Link" },
  { q: "What is a portal with all resonators called?", m: "Full Portal,Complete Portal,Max Portal,Prime Portal" },
  { q: "What is an empty portal called?", m: "Neutral Portal,Zero Portal,Empty Portal,Blank Portal" }
];